services:
  web:
    environment:
      HOST: 0.0.0.0
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:3000/api/v1/health | grep -q '\"status\":\"ok\"'"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
