
services:
  web:
    build:
      args:
        NEXT_PUBLIC_SITE_URL: https://vinops.online
      context: ./frontend
      dockerfile: Dockerfile
    image: vinops-web:latest
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:3000/en >/dev/null || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 6
      start_period: 20s
    networks: [webnet]

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    depends_on:
      web:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks: [webnet]

networks:
  webnet: {}

volumes:
  caddy_data: {}
  caddy_config: {}
