services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: vinops/web
    environment:
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
    ports:
      - "3000:3000"
