blank_issues_enabled: false
contact_links:
  - name: Контекст + логи перед вопросом ИИ
    url: https://github.com/KestutisTreciokas/vinops/tree/main/context
    about: Сначала собери контекст `./bin/ctx.sh`, затем заводи issue/обращайся к ИИ.
