name: Build & Push to GHCR
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}
permissions:
  contents: read
  packages: write
jobs:
  build-push:
    runs-on: ubuntu-latest
    concurrency:
      group: ghcr-kestutistreciokas-vinops-main
      cancel-in-progress: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set SHORT_SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push WEB
        if: ${{ hashFiles('frontend/package.json') != '' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/kestutistreciokas/vinops-web:prod
            ghcr.io/kestutistreciokas/vinops-web:${{ env.SHORT_SHA }}
      - name: Build & Push API
        if: ${{ hashFiles('backend/package.json', 'backend/pyproject.toml', 'backend/requirements.txt', 'backend/go.mod', 'backend/composer.json') != '' }}
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ghcr.io/KestutisTreciokas/vinops-api:prod
            ghcr.io/KestutisTreciokas/vinops-api:${{ env.SHORT_SHA }}
